export const ADD_TOTAL="ADD_TOTAL"
export const ADD_DATE="ADD_DATE"

export const LOGIN_LOADING="LOGIN_LOADING"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_ERROR="LOGIN_ERROR"

export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"